name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  lint-c:
    runs-on: ubuntu-latest
    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - uses: actions/checkout@v2
      - name: Lint C
        run: |
          clang-format --Werror --dry-run bpf/ingress.c
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - name: Lint Go
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -u golang.org/x/tools/cmd/goimports
          go get -u honnef.co/go/tools/cmd/staticcheck
          go vet ./...
          staticcheck ./...
          diff -u <(echo -n) <(find . -name '*.go' | xargs goimports -d)
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - name: Test
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          sudo go test -cover ./...
