name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  lint-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - name: Lint C
        run: |
          clang-format --Werror --dry-run bpf/ingress.c

  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Go
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
          skip-build-cache: true
          skip-pkg-cache: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - name: Test
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          sudo go test -cover ./...
